# Generated by Django 5.0.14 on 2026-09-02 08:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import fees.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=20)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('closed', 'Closed')], default='planning', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=30)),
                ('ladder_order', models.PositiveSmallIntegerField()),
                ('stage', models.CharField(choices=[('pre_primary', 'Pre-primary'), ('primary', 'Primary'), ('middle', 'Middle'), ('secondary', 'Secondary'), ('puc', 'Pre-university')], max_length=15)),
                ('requires_explicit_optin', models.BooleanField(default=False, help_text='Promotion into this level must be chosen per student.')),
                ('requires_stream', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False, help_text='Students exit to alumni after this level.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ladder_order'],
            },
        ),
        migrations.CreateModel(
            name='PromotionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committed', 'Committed'), ('reversed', 'Reversed')], default='draft', max_length=10)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('carry_forward_arrears', models.BooleanField(default=True)),
                ('block_on_dues', models.BooleanField(default=False, help_text='School policy: refuse promotion if dues outstanding.')),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_out', to='fees.academicyear')),
                ('to_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_in', to='fees.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('roll_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('admission_type', models.CharField(choices=[('new', 'New admission'), ('carry_over', 'Promoted from previous year'), ('repeat', 'Repeating the class'), ('readmission', 'Re-admission')], max_length=15)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('promoted', 'Promoted'), ('detained', 'Detained'), ('tc_issued', 'TC issued'), ('passed_out', 'Passed out'), ('left', 'Left mid-year')], default='pending', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='fees.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='fees.classlevel')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('promotion_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='fees.promotionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.SlugField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('logo_key', models.CharField(blank=True, max_length=500)),
                ('receipt_footer', models.TextField(blank=True, default='Education services are exempt from GST. This is a computer generated receipt.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='promotionbatch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reversal_reason', models.CharField(blank=True, max_length=200)),
                ('receipt_no', models.CharField(max_length=40)),
                ('amount', fees.models.MoneyField(help_text='Amount in paise (integer).', validators=[django.core.validators.MinValueValidator(1)])),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net banking'), ('neft', 'NEFT / IMPS'), ('cheque', 'Cheque'), ('dd', 'Demand draft')], max_length=12)),
                ('clearing_status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('cleared_on', models.DateField(blank=True, null=True)),
                ('instrument_ref', models.CharField(blank=True, help_text='Cheque no, UTR, UPI ref.', max_length=100)),
                ('gateway', models.CharField(blank=True, max_length=30)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('convenience_fee', fees.models.MoneyField(default=0, help_text='Amount in paise (integer).', validators=[django.core.validators.MinValueValidator(0)])),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.enrollment')),
                ('reversed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverses', to='fees.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invoice_no', models.CharField(max_length=40)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_on', models.DateField()),
                ('student_name_at_issue', models.CharField(max_length=150)),
                ('class_at_issue', models.CharField(max_length=40)),
                ('pdf_key', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fees.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=80)),
                ('basis', models.CharField(choices=[('per_class', 'Priced per class'), ('per_slab', 'Priced per slab (transport routes etc.)'), ('flat', 'Same for everyone')], default='per_class', max_length=12)),
                ('is_one_time', models.BooleanField(default=False, help_text='Charged once at admission, e.g. admission fee.')),
                ('is_optional', models.BooleanField(default=False, help_text='Opt-in per student, e.g. transport, hostel.')),
                ('is_refundable', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school'),
        ),
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice')], max_length=10)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=50)),
                ('body_en', models.TextField()),
                ('body_local', models.TextField(blank=True, help_text='Kannada / Hindi text.')),
                ('effective_from', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reversal_reason', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(choices=[('sibling', 'Sibling discount'), ('staff_ward', 'Staff ward'), ('rte', 'RTE quota'), ('merit', 'Merit scholarship'), ('hardship', 'Financial hardship'), ('other', 'Other')], max_length=15)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('amount', fees.models.MoneyField(help_text='Amount in paise (integer).', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_government_reimbursed', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverses', to='fees.concession')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to='fees.enrollment')),
                ('fee_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fees.feehead')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
        ),
        migrations.AddField(
            model_name='classlevel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school'),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reversal_reason', models.CharField(blank=True, max_length=200)),
                ('head_name', models.CharField(max_length=80)),
                ('amount', fees.models.MoneyField(help_text='Amount in paise (integer).', validators=[django.core.validators.MinValueValidator(0)])),
                ('term_no', models.PositiveSmallIntegerField(default=1)),
                ('due_on', models.DateField()),
                ('source', models.CharField(choices=[('structure', 'From fee structure'), ('arrear', 'Carried forward arrear'), ('manual', 'Manually added')], default='structure', max_length=12)),
                ('is_arrear', models.BooleanField(default=False, help_text='Carried forward from a previous year.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverses', to='fees.charge')),
                ('source_year', models.ForeignKey(blank=True, help_text='For arrears: the year the dues originally arose in.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fees.academicyear')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='fees.enrollment')),
                ('fee_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fees.feehead')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='fees.invoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
            options={
                'ordering': ['due_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('amount', fees.models.MoneyField(help_text='Amount in paise (integer).', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.charge')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fees.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='fees.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='fees.classlevel')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
            options={
                'ordering': ['class_level__ladder_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='fees.section'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=40)),
                ('combination', models.CharField(blank=True, max_length=40)),
                ('applies_to_stage', models.CharField(choices=[('pre_primary', 'Pre-primary'), ('primary', 'Primary'), ('middle', 'Middle'), ('secondary', 'Secondary'), ('puc', 'Pre-university')], default='puc', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('amount', fees.models.MoneyField(help_text='Amount in paise (integer).', validators=[django.core.validators.MinValueValidator(0)])),
                ('term_no', models.PositiveSmallIntegerField(default=1, help_text='1, 2, 3 for termwise instalments.')),
                ('due_on', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='fees.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='fees.classlevel')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='fees.feehead')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fees.stream')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fees.stream'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('admission_no', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('admitted_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('alumni', 'Alumni'), ('transferred', 'Transferred out'), ('left', 'Left')], default='active', max_length=15)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('photo_key', models.CharField(blank=True, max_length=500)),
                ('deidentified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='fees.student'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('purpose', models.CharField(choices=[('fee_admin', 'Fee administration'), ('academic_records', 'Academic records'), ('sms_whatsapp', 'SMS / WhatsApp communication'), ('photo_publication', 'Photographs and publicity'), ('transport_tracking', 'School bus tracking')], max_length=25)),
                ('granted_by_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=40)),
                ('verification_method', models.CharField(choices=[('digilocker', 'DigiLocker verified token'), ('in_person_id', 'In-person ID check at office'), ('signed_form', 'Wet-signed form on record')], max_length=20)),
                ('verification_ref', models.CharField(blank=True, help_text='DigiLocker token or scanned form key. Never store raw Aadhaar.', max_length=200)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='fees.consentnotice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fees.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='fees.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', 'received_on'], name='fees_paymen_school__96c7d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('school', 'receipt_no'), name='uniq_receipt_no_per_school'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_payment_id', ''), _negated=True), fields=('gateway', 'gateway_payment_id'), name='uniq_gateway_payment_id'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('school', 'invoice_no'), name='uniq_invoice_no_per_school'),
        ),
        migrations.AddConstraint(
            model_name='feehead',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_fee_head_per_school'),
        ),
        migrations.AddConstraint(
            model_name='documentcounter',
            constraint=models.UniqueConstraint(fields=('school', 'doc_type', 'fiscal_year'), name='uniq_doc_counter'),
        ),
        migrations.AddConstraint(
            model_name='consentnotice',
            constraint=models.UniqueConstraint(fields=('school', 'purpose', 'version'), name='uniq_notice_version'),
        ),
        migrations.AddConstraint(
            model_name='concession',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='concession_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(fields=('school', 'ladder_order'), name='uniq_ladder_order_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_class_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['enrollment', 'due_on'], name='fees_charge_enrollm_c0736b_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['school', 'due_on'], name='fees_charge_school__e4055f_idx'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='charge_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(check=models.Q(('is_arrear', False), ('source_year__isnull', False), _connector='OR'), name='arrear_requires_source_year'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('payment', 'charge'), name='uniq_allocation_per_payment_charge'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_year_per_school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(check=models.Q(('ends_on__gt', models.F('starts_on'))), name='year_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'class_level', 'name'), name='uniq_section_per_class_year'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('school', 'name', 'combination'), name='uniq_stream_per_school'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'class_level', 'fee_head', 'stream', 'term_no'), name='uniq_fee_structure_line'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='fee_structure_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'full_name'], name='fees_studen_school__1337ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'admission_no'), name='uniq_admission_no_per_school'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'academic_year', 'class_level'], name='fees_enroll_school__64b863_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('school', 'student', 'academic_year'), name='uniq_enrollment_per_student_year'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_no__isnull', False)), fields=('school', 'section', 'roll_no'), name='uniq_roll_no_per_section'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['school', 'student', 'purpose'], name='fees_consen_school__9d59ad_idx'),
        ),
    ]
